[project]
name = 'Transparent-Educational-Scholarship-Distribution'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.donor-managment]
path = 'contracts/donor-managment.clar'
clarity_version = 2
epoch = 2.5

[contracts.student-verification]
path = 'contracts/student-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
